require 'crass'
require 'oga'
require 'fugazi'

require_relative 'placebo/dom'
require_relative 'placebo/html_parser'
require_relative 'placebo/css_parser'
require_relative 'placebo/style_tree'
require_relative 'placebo/layout'
require_relative 'placebo/raster'
require_relative 'placebo/open'
